# Generated by Django 5.1.6 on 2025-02-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='course',
        ),
    ]
