# Generated by Django 5.1.6 on 2025-02-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_rename_degree_education_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='university',
            new_name='institution',
        ),
    ]
